[package]
authors = ["David Fisher <ddfisher@dropbox.com>", "clemens"]
name = "ruba"
version = "0.1.0"

[dependencies]
futures = "0.2.0-alpha"
futures-channel = "0.2.0-alpha"
csv = "0.15.0"
heapsize = "0.3.8"
itertools = "0.5.9"
nom = "^3.2.1"
num = "0.1.36"
regex = "0.2"
rustyline = "1.0.0"
serde_json = "0.9.6"
time = "0.1.36"
serde_derive = "1.0"
serde = "1.0"
bincode = "0.9.2"
seahash = "3.0.5"
bit-vec = "0.4.4"
num_cpus = "1.0"
chrono = "0.4.0"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4"

[dev-dependencies]
env_logger = "0.5.6"


[features]
default=[]
trace=[]